# Generated by Django 4.2.17 on 2026-03-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('to_do', 'To Do'), ('in_progress', 'In Progress'), ('ready', 'Ready'), ('outdated', 'Outdated')], default='to_do', max_length=20),
        ),
    ]
